// Generated by CoffeeScript 1.10.0
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['spectrum/Renderer', 'underscore'], function(Renderer, _) {
    var Compiler;
    return Compiler = (function() {
      function Compiler(ctx) {
        this.ctx = ctx;
        this.compile = bind(this.compile, this);
      }

      Compiler.prototype.compile = function(code) {
        var error, error1, error2, error3, error4, obj, pre, r;
        r = null;
        try {
          obj = CoffeeScript["eval"](code, {
            bare: true
          });
          pre = {};
          r = _.extend(pre, new Renderer(this.ctx));
          r = _.extend(r, obj);
          if (r != null) {
            if (r.init != null) {
              try {
                r.init();
              } catch (error1) {
                error = error1;
                this.onInitError(error);
                return;
              }
            }
            if (r.step != null) {
              try {
                r.step();
              } catch (error2) {
                error = error2;
                this.onStepError(error);
                return;
              }
            }
            if (r.render != null) {
              try {
                r.render();
              } catch (error3) {
                error = error3;
                this.onRenderError(error);
                return;
              }
            }
          }
          pre = {};
          r = {};
          r = _.extend(pre, new Renderer(this.ctx));
          r = _.extend(r, obj);
          return r;
        } catch (error4) {
          error = error4;
          return this.onCompilationError(error);
        }
      };

      Compiler.prototype.onCompilationError = function(error) {
        return console.log("onCompilationError()", error.message);
      };

      Compiler.prototype.onInitError = function(error) {
        return console.log("onInitializationError()");
      };

      Compiler.prototype.onNoMainClassError = function() {
        return console.log("onNoMainClassError()");
      };

      Compiler.prototype.onRenderError = function(error) {
        return console.log("onRenderError()", error.message);
      };

      Compiler.prototype.onStepError = function(error) {
        return console.log("onStepError()");
      };

      return Compiler;

    })();
  });

}).call(this);
