// Generated by CoffeeScript 1.9.3
(function() {
  define(function() {
    var Vector;
    return Vector = (function() {
      Vector.Zero = new Vector(0, 0);

      Vector.distance = function(v1, v2) {
        var x, y;
        x = v1.x - v2.x;
        y = v1.y - v2.y;
        return Math.sqrt(x * x + y * y);
      };

      function Vector(x1, y1) {
        this.x = x1 != null ? x1 : 0;
        this.y = y1 != null ? y1 : 0;
      }

      Vector.prototype.length = function() {
        return Math.sqrt(this.x * this.x + this.y * this.y);
      };

      Vector.prototype.add = function(v) {
        return new Vector(this.x + v.x, this.y + v.y);
      };

      Vector.prototype.sub = function(v) {
        return new Vector(this.x - v.x, this.y - v.y);
      };

      Vector.prototype.div = function(n) {
        return new Vector(this.x / n, this.y / n);
      };

      Vector.prototype.mult = function(v) {
        return new Vector(this.x * v.x, this.y * v.y);
      };

      Vector.prototype.scale = function(n) {
        return new Vector(this.x * n, this.y * n);
      };

      Vector.prototype.normalized = function(v) {
        var len;
        len = this.length();
        if (len === 0.0) {
          return this.Zero();
        } else {
          return this.div(len);
        }
      };

      return Vector;

    })();
  });

}).call(this);
