// Generated by CoffeeScript 1.6.3
(function() {
  define(['renderer', 'player', 'compiler'], function(Renderer, Player, Compiler) {
    var Spectrum;
    return Spectrum = (function() {
      function Spectrum() {}

      Spectrum.Player = Player;

      Spectrum.Compiler = Compiler;

      Spectrum.Renderer = Renderer;

      return Spectrum;

    })();
  });

}).call(this);
