// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    Array.shuffle = function(a) {
      var copy, r, result;
      result = [];
      copy = a.slice();
      console.log(copy);
      while (copy.length > 0) {
        r = Math.floor(Math.random() * copy.length);
        result.push(copy.splice(r, 1)[0]);
      }
      return result;
    };
    Math.TWO_PI = Math.PI * 2;
    Math.distance = function(x1, y1, x2, y2) {
      var dx, dy;
      dx = x1 - x2;
      dy = y1 - y2;
      dx *= dx;
      dy *= dy;
      return Math.sqrt(dx + dy);
    };
    Math.interpolateLin = function(n, min, max) {
      return min + ((max - min) * n);
    };
    Math.normalize = function(n, min, max) {
      return (n - min) / (max - min);
    };
    Math.randomInRange = function(min, max, round) {
      var n;
      if (round == null) {
        round = false;
      }
      n = min + (max - min) * Math.random();
      if (round) {
        return Math.round(n);
      }
      return n;
    };
    Math.roundTo = function(n, decimals) {
      return Math.round(n * Math.pow(10, decimals)) / Math.pow(10, decimals);
    };
    Math.roundToMultiple = function(n, multiple) {
      return multiple * Math.round(n / multiple);
    };
    Math.toRadians = function(degrees) {
      return Math.PI * degrees / 180;
    };
    return Math.transpose = function(n, min1, max1, min2, max2) {
      return Math.interpolateLin(Math.normalize(n, min1, max1), min2, max2);
    };
  });

}).call(this);
