// Generated by CoffeeScript 1.6.3
(function() {
  define(function() {
    var Dispatcher;
    return Dispatcher = (function() {
      function Dispatcher() {}

      Dispatcher.prototype.callbacks = {};

      Dispatcher.prototype.add = function(eventName, callback) {
        var _base;
        (_base = this.callbacks)[eventName] || (_base[eventName] = []);
        return this.callbacks[eventName].push(callback);
      };

      Dispatcher.prototype.dispatch = function(eventName, data) {
        var callback, _i, _len, _results;
        this.chain = this.callbacks[eventName];
        if (typeof chain !== "undefined" && chain !== null) {
          _results = [];
          for (_i = 0, _len = chain.length; _i < _len; _i++) {
            callback = chain[_i];
            _results.push(callback(data));
          }
          return _results;
        }
      };

      return Dispatcher;

    })();
  });

}).call(this);
