// Generated by CoffeeScript 1.6.3
(function() {
  var a, additions, m, _i, _j, _len, _len1, _ref;

  window.Spectrum = {};

  _ref = Object.getOwnPropertyNames(Math);
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    m = _ref[_i];
    window[m] = Math[m];
  }

  additions = [["TWO_PI", Math.PI * 2]];

  for (_j = 0, _len1 = additions.length; _j < _len1; _j++) {
    a = additions[_j];
    window[a[0]] = a[1];
  }

}).call(this);
