// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['compiler'], function(Compiler) {
    var Player;
    return Player = (function() {
      Player.prototype.running = false;

      function Player(canvas) {
        this.canvas = canvas;
        this.stop = __bind(this.stop, this);
        this.step = __bind(this.step, this);
        this.setRenderer = __bind(this.setRenderer, this);
        this.render = __bind(this.render, this);
        this.pause = __bind(this.pause, this);
        this.run = __bind(this.run, this);
        this.loop = __bind(this.loop, this);
        this.getAnimationCallback = __bind(this.getAnimationCallback, this);
        console.log(Compiler);
        this.frame = 0;
        this.width = this.canvas.clientWidth;
        this.height = this.canvas.clientHeight;
        this.ctx = canvas.getContext("2d");
        this.renderer = null;
        this.loop();
        this.canvas.addEventListener("mousedown", this.onMouseEvent, true);
        this.canvas.addEventListener("mousemove", this.onMouseEvent, true);
        this.canvas.addEventListener("mouseout", this.onMouseEvent, true);
        this.canvas.addEventListener("mouseover", this.onMouseEvent, true);
        this.canvas.addEventListener("mouseup", this.onMouseEvent, true);
      }

      Player.prototype.getAnimationCallback = function() {
        return window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame || setTimeout(callback, 1000 / 60);
      };

      Player.prototype.loop = function() {
        this.getAnimationCallback()(this.loop);
        if ((this.renderer != null) && this.running && !this.renderer["static"]) {
          this.step();
          return this.render();
        }
      };

      Player.prototype.run = function() {
        return this.running = true;
      };

      Player.prototype.onMouseEvent = function(event) {
        var x, y;
        x = event.offsetX;
        y = event.offsetY;
        if (this.renderer != null) {
          switch (event.type) {
            case "mousedown":
              if (this.renderer.onMouseDown != null) {
                return this.renderer.onMouseDown(x, y);
              }
              break;
            case 'mousemove':
              if (this.renderer.onMouseMove != null) {
                return this.renderer.onMouseMove(x, y);
              }
              break;
            case 'mouseout':
              if (this.renderer.onMouseOut != null) {
                return this.renderer.onMouseOut(x, y);
              }
              break;
            case 'mouseover':
              if (this.renderer.onMouseEnter != null) {
                return this.renderer.onMouseEnter(x, y);
              }
              break;
            case 'mouseup':
              if (this.renderer.onMouseUp != null) {
                return this.renderer.onMouseUp(x, y);
              }
          }
        }
      };

      Player.prototype.pause = function() {
        return this.running = false;
      };

      Player.prototype.render = function() {
        if (this.renderer.clear != null) {
          this.renderer.clear();
        }
        if (this.renderer.render != null) {
          return this.renderer.render();
        }
      };

      Player.prototype.setRenderer = function(newRenderer) {
        this.renderer = newRenderer;
        this.renderer.width = this.canvas.clientWidth;
        return this.renderer.height = this.canvas.clientHeight;
      };

      Player.prototype.step = function() {
        if (this.renderer.looping && this.renderer.duration > 0) {
          if (this.frame > this.renderer.duration) {
            this.frame = 0;
          }
        }
        this.frame++;
        this.renderer.frame = this.frame;
        this.renderer.width = this.canvas.clientWidth;
        this.renderer.height = this.canvas.clientHeight;
        if (this.renderer.step != null) {
          return this.renderer.step();
        }
      };

      Player.prototype.stop = function() {
        this.frame = 0;
        this.running = false;
        this.ctx.clearRect(0, 0, this.width, this.height);
        if (this.renderer != null) {
          if (this.renderer.clear != null) {
            return this.renderer.clear();
          }
        }
      };

      return Player;

    })();
  });

}).call(this);
