// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['renderer'], function(Renderer) {
    var Basic, _ref;
    return Basic = (function(_super) {
      __extends(Basic, _super);

      function Basic() {
        _ref = Basic.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Basic.prototype.init = function() {
        this.bg = "#222222";
        this.cx = this.width * .5;
        return this.cy = this.height * .5;
      };

      Basic.prototype.render = function() {
        this.font("bold 80pt Baskerville");
        this.color("#ffffff");
        this.text(165, 250, "SPECTRUM", false);
        this.color("#d13737");
        this.point(this.cx - 25, this.cy + 20, 10);
        this.color("45d137");
        this.point(this.cx, this.cy + 20, 10);
        this.color("#3762d1");
        return this.point(this.cx + 25, this.cy + 20, 10);
      };

      return Basic;

    })(Renderer);
  });

}).call(this);
