// Generated by CoffeeScript 1.6.3
(function() {
  require({
    paths: {
      spectrum: '../lib/spectrum/Spectrum',
      player: '../lib/spectrum/Player',
      compiler: '../lib/spectrum/Compiler',
      renderer: '../lib/spectrum/Renderer',
      utils: '../lib/spectrum/Utils',
      dispatcher: '../lib/spectrum/Dispatcher'
    }
  });

}).call(this);
