// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    return require.config({
      paths: {
        coffee: '../lib/vendor/coffee-script',
        spectrum: '../lib/spectrum/Spectrum',
        player: '../lib/spectrum/Player',
        compiler: '../lib/spectrum/Compiler',
        renderer: '../lib/spectrum/Renderer',
        env: '../lib/spectrum/Env'
      }
    });
  });

}).call(this);
