// Generated by CoffeeScript 1.9.3
(function() {
  require({
    paths: {
      demos: '../js/',
      spectrum: '../../js/',
      coffeerithms: '../../../coffeerithms/lib'
    }
  });

}).call(this);
