// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  define(['renderer'], function(Renderer) {
    var HitTests, _ref;
    return HitTests = (function(_super) {
      __extends(HitTests, _super);

      function HitTests() {
        _ref = HitTests.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      HitTests.prototype.init = function() {
        this.centerX = this.width * .5;
        this.centerY = this.height * .5;
        this.rect1 = [this.centerX - 50, this.centerY - 50, 100, 100];
        this.circ1 = [this.centerX - 200, this.centerY, 50];
        this.tri1 = [[this.centerX + 200, this.centerY - 50], [this.centerX + 150, this.centerY + 50], [this.centerX + 400, this.centerY + 50]];
        return this.ring1 = [this.centerX, this.centerY + 150, 20, 50, 16, 36];
      };

      HitTests.prototype.render = function() {
        if (Math.hitTestRectangle.apply(Math, [this.mouseX, this.mouseY].concat(__slice.call(this.rect1)))) {
          this.color("#000000");
        } else {
          this.color("#ffffff");
        }
        this.rectangle.apply(this, this.rect1);
        if (Math.hitTestCircle.apply(Math, [this.mouseX, this.mouseY].concat(__slice.call(this.circ1)))) {
          this.color("#000000");
        } else {
          this.color("#ffffff");
        }
        this.circle.apply(this, this.circ1);
        if (Math.hitTestTriangle.apply(Math, [this.mouseX, this.mouseY].concat(__slice.call(this.tri1)))) {
          this.color("#000000");
        } else {
          this.color("#ffffff");
        }
        this.shape(this.tri1, true, true);
        if (Math.hitTestRing.apply(Math, [this.mouseX, this.mouseY].concat(__slice.call(this.ring1)))) {
          this.color("#000000");
        } else {
          this.color("#ffffff");
        }
        return this.polygonRing.apply(this, this.ring1);
      };

      return HitTests;

    })(Renderer);
  });

}).call(this);
