// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['renderer'], function(Renderer) {
    var KeyEvents, _ref;
    return KeyEvents = (function(_super) {
      __extends(KeyEvents, _super);

      function KeyEvents() {
        _ref = KeyEvents.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      KeyEvents.prototype.init = function() {
        return this.keyInfo = '';
      };

      KeyEvents.prototype.step = function() {};

      KeyEvents.prototype.render = function() {
        this.color('black');
        return this.text(10, 30, this.keyInfo);
      };

      KeyEvents.prototype.onKeyDown = function(keyCode, altKey, ctrlKey, shiftKey, timeStamp) {
        return this.keyInfo = 'keyCode: ' + keyCode + ', altKey: ' + altKey + ', ctrlKey: ' + ctrlKey + ', shiftKey: ' + shiftKey + ', timeStamp: ' + timeStamp;
      };

      return KeyEvents;

    })(Renderer);
  });

}).call(this);
