// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    return require.config({
      baseUrl: "../lib/",
      paths: {
        compiler: 'Compiler',
        env: 'Env',
        play: 'Player'
      }
    });
  });

}).call(this);
