// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['renderer'], function(Renderer) {
    var Motion, _ref;
    return Motion = (function(_super) {
      __extends(Motion, _super);

      function Motion() {
        _ref = Motion.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Motion.prototype.init = function() {
        this.n = 0;
        this.s = 0;
        this.bg = "#222222";
        this.cx = this.width * .5;
        return this.cy = this.height * .5;
      };

      Motion.prototype.step = function() {
        this.n += .01;
        return this.s = this.sin(this.n);
      };

      Motion.prototype.render = function() {
        this.color("#ffcc00");
        this.alpha(this.abs(this.s));
        this.saveTransform();
        this.translate(this.cx, this.cy);
        this.rotate(this.s);
        this.polygon(0, 0, 100, 2 + this.ceil(this.abs(this.s) * 10));
        return this.restoreTransform();
      };

      return Motion;

    })(Renderer);
  });

}).call(this);
