// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['renderer'], function(Renderer) {
    var PolygonRings, _ref;
    return PolygonRings = (function(_super) {
      __extends(PolygonRings, _super);

      function PolygonRings() {
        _ref = PolygonRings.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      PolygonRings.prototype.init = function() {
        this.cx = this.width * .5;
        this.cy = this.height * .5;
        return this.poly1 = [0, 0, 30, 80, 6, 3, Math.PI * 2, false];
      };

      PolygonRings.prototype.render = function() {
        this.color("white");
        this.polygonRing(this.cx, this.cy, 20, 40, 3, 6);
        this.saveTransform();
        this.translate(this.cx - 200, this.cy);
        this.polygonRing.apply(this, this.poly1);
        this.restoreTransform();
        this.saveTransform();
        this.translate(this.cx + 200, this.cy);
        this.rotate(Math.PI);
        this.polygonRing.apply(this, this.poly1);
        return this.restoreTransform();
      };

      return PolygonRings;

    })(Renderer);
  });

}).call(this);
