// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['renderer'], function(Renderer) {
    var Shape, _ref;
    return Shape = (function(_super) {
      __extends(Shape, _super);

      function Shape() {
        _ref = Shape.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Shape.prototype.init = function() {
        var p, _i, _len, _ref1, _results;
        this.shapeData1 = [[30, 30], [200, 50], [220, 250], [100, 280], [30, 200]];
        this.shapeData2 = [];
        this.shapeData3 = [];
        _ref1 = this.shapeData1;
        _results = [];
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          p = _ref1[_i];
          this.shapeData2.push([p[0] + 300, p[1]]);
          _results.push(this.shapeData3.push([p[0] + 600, p[1]]));
        }
        return _results;
      };

      Shape.prototype.step = function() {};

      Shape.prototype.render = function() {
        this.color("white");
        this.shape(this.shapeData1, false, false);
        this.shape(this.shapeData2, true, true);
        return this.shape(this.shapeData3, false, true);
      };

      return Shape;

    })(Renderer);
  });

}).call(this);
