// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['renderer'], function(Renderer) {
    var SynthesisVisualization, _ref;
    return SynthesisVisualization = (function(_super) {
      __extends(SynthesisVisualization, _super);

      function SynthesisVisualization() {
        _ref = SynthesisVisualization.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      SynthesisVisualization.prototype.init = function() {
        var AudioContext;
        AudioContext = window.AudioContext || window.webkitAudioContext;
        if (AudioContext != null) {
          this.audioCtx = new AudioContext();
          this.oscillator = this.audioCtx.createOscillator();
          this.gain = this.audioCtx.createGain();
          this.analyzer = this.audioCtx.createAnalyser();
          this.oscillator.connect(this.analyzer);
          this.analyzer.connect(this.gain);
          this.gain.connect(this.audioCtx.destination);
          this.freqData = new Uint8Array(this.analyzer.frequencyBinCount);
          this.stepInterval = 5;
          this.oscillator.start(0);
          this.playing = true;
        }
        return this.bg = "#222222";
      };

      SynthesisVisualization.prototype.step = function() {
        if ((this.audioCtx != null) && this.stepCount % this.stepInterval === 0 && this.playing) {
          this.gain.gain.value = Math.clamp(Math.transpose(this.mouseY, 0, this.height, 1, 0), 0, 1);
          this.oscillator.frequency.value = Math.clamp(Math.transpose(this.mouseX, 0, this.width, 20, 2000), 20, 2000);
          return this.analyzer.getByteFrequencyData(this.freqData);
        }
      };

      SynthesisVisualization.prototype.render = function() {
        var value, x, _i, _ref1, _results;
        this.color("#dddddd");
        if (this.audioCtx != null) {
          this.text(10, 20, "x: frequency " + Math.roundTo(this.oscillator.frequency.value, 2));
          this.text(10, 35, "y: amplitude " + Math.roundTo(this.gain.gain.value, 2));
          this.text(10, 50, "Click to toggle playback");
          if (this.playing) {
            _results = [];
            for (x = _i = 0, _ref1 = this.freqData.length * .5; 0 <= _ref1 ? _i <= _ref1 : _i >= _ref1; x = 0 <= _ref1 ? ++_i : --_i) {
              value = this.freqData[x] * 1.55555;
              _results.push(this.rectangle(x * 10, this.height - value, 3, value));
            }
            return _results;
          }
        } else {
          this.color("#ff0000");
          return this.text(20, 20, "AudioContext not available in this browser");
        }
      };

      SynthesisVisualization.prototype.onMouseDown = function(x, y) {
        if (this.playing) {
          this.gain.gain.value = 0;
        } else {
          this.gain.gain.value = 1;
        }
        return this.playing = !this.playing;
      };

      return SynthesisVisualization;

    })(Renderer);
  });

}).call(this);
